"""replace_team_size_with_min_max_team_size

Revision ID: 025f5d0e1c85
Revises: f65968cf9b5b
Create Date: 2026-06-14 22:28:18.571753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '025f5d0e1c85'
down_revision: Union[str, Sequence[str], None] = 'f65968cf9b5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add with a server_default so existing rows get a value, then drop the default
    op.add_column('event_team_settings', sa.Column('min_team_size', sa.Integer(), nullable=False, server_default='2'))
    op.add_column('event_team_settings', sa.Column('max_team_size', sa.Integer(), nullable=False, server_default='4'))
    op.alter_column('event_team_settings', 'min_team_size', server_default=None)
    op.alter_column('event_team_settings', 'max_team_size', server_default=None)
    op.drop_column('event_team_settings', 'team_size')
    op.drop_column('event_team_settings', 'min_per_institution')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_team_settings', sa.Column('min_per_institution', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('event_team_settings', sa.Column('team_size', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('event_team_settings', 'max_team_size')
    op.drop_column('event_team_settings', 'min_team_size')
    # ### end Alembic commands ###
