"""Add arrival/return tickets, processing lock, and expense breakdown

Revision ID: 0df065ecb10a
Revises: 90bb1271e091
Create Date: 2026-06-17 21:28:43.038646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0df065ecb10a'
down_revision: Union[str, Sequence[str], None] = '90bb1271e091'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_travel', sa.Column('arrival_ticket_url', sa.Text(), nullable=True))
    op.add_column('team_travel', sa.Column('arrival_ticket_name', sa.Text(), nullable=True))
    op.add_column('team_travel', sa.Column('arrival_ticket_uploaded_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('team_travel', sa.Column('return_ticket_url', sa.Text(), nullable=True))
    op.add_column('team_travel', sa.Column('return_ticket_name', sa.Text(), nullable=True))
    op.add_column('team_travel', sa.Column('return_ticket_uploaded_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('team_travel', sa.Column('travel_processing_started', sa.Boolean(), nullable=True))
    op.add_column('travel_reimbursement_claims', sa.Column('arrival_expense', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('travel_reimbursement_claims', sa.Column('return_expense', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('travel_reimbursement_claims', sa.Column('other_expense', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('travel_reimbursement_claims', 'other_expense')
    op.drop_column('travel_reimbursement_claims', 'return_expense')
    op.drop_column('travel_reimbursement_claims', 'arrival_expense')
    op.drop_column('team_travel', 'travel_processing_started')
    op.drop_column('team_travel', 'return_ticket_uploaded_at')
    op.drop_column('team_travel', 'return_ticket_name')
    op.drop_column('team_travel', 'return_ticket_url')
    op.drop_column('team_travel', 'arrival_ticket_uploaded_at')
    op.drop_column('team_travel', 'arrival_ticket_name')
    op.drop_column('team_travel', 'arrival_ticket_url')
    # ### end Alembic commands ###
