"""update distribution rules schema

Revision ID: 134e6897411f
Revises: 17a6a6a131ed
Create Date: 2026-05-28 23:32:16.649229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '134e6897411f'
down_revision: Union[str, Sequence[str], None] = '17a6a6a131ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distribution_rules', sa.Column('min_team_size', sa.Integer(), nullable=False))
    op.add_column('distribution_rules', sa.Column('custom_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('distribution_rules', 'custom_rules')
    op.drop_column('distribution_rules', 'min_team_size')
    # ### end Alembic commands ###
