"""create events table

Revision ID: 17a6a6a131ed
Revises: 9ca348a37e76
Create Date: 2026-05-24 23:45:33.791901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17a6a6a131ed'
down_revision: Union[str, Sequence[str], None] = '9ca348a37e76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.Text(), nullable=True),
    sa.Column('decision_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('distribution_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('team_size', sa.Integer(), nullable=False),
    sa.Column('max_per_institution', sa.Integer(), nullable=True),
    sa.Column('required_skills', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('balance_by', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('exclusions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluators',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token'),
    sa.UniqueConstraint('event_id', 'email')
    )
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('challenge', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('final_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('communications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Text(), nullable=False),
    sa.Column('recipient_type', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('approval_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approval_id'], ['approval_requests.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('evaluator_id', sa.UUID(), nullable=False),
    sa.Column('scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('overall', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('assessment_guide', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['evaluator_id'], ['evaluators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'evaluator_id')
    )
    op.create_table('score_anomalies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('evaluator_id', sa.UUID(), nullable=True),
    sa.Column('flagged_score', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('panel_average', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('deviation', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('resolved_by', sa.Text(), nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['evaluator_id'], ['evaluators.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'participant_id')
    )
    op.create_table('communication_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('communication_id', sa.UUID(), nullable=True),
    sa.Column('recipient_email', sa.Text(), nullable=False),
    sa.Column('recipient_name', sa.Text(), nullable=True),
    sa.Column('personalized_body', sa.Text(), nullable=True),
    sa.Column('sendgrid_message_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['communication_id'], ['communications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('communication_logs')
    op.drop_table('team_members')
    op.drop_table('score_anomalies')
    op.drop_table('evaluations')
    op.drop_table('communications')
    op.drop_table('teams')
    op.drop_table('evaluators')
    op.drop_table('distribution_rules')
    op.drop_table('approval_requests')
    # ### end Alembic commands ###
