"""Add travel fields

Revision ID: 2af180934321
Revises: 5a5b8974cac6
Create Date: 2026-06-17 23:59:33.772931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2af180934321'
down_revision: Union[str, Sequence[str], None] = '5a5b8974cac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_travel', sa.Column('arrival_date', sa.Date(), nullable=True))
    op.add_column('team_travel', sa.Column('arrival_time', sa.Time(), nullable=True))
    op.add_column('team_travel', sa.Column('arrival_airport_or_station', sa.Text(), nullable=True))
    op.add_column('team_travel', sa.Column('departure_date', sa.Date(), nullable=True))
    op.add_column('team_travel', sa.Column('departure_time', sa.Time(), nullable=True))
    op.add_column('team_travel', sa.Column('departure_airport_or_station', sa.Text(), nullable=True))
    op.add_column('team_travel', sa.Column('flight_or_train_number', sa.Text(), nullable=True))
    op.add_column('team_travel', sa.Column('pnr_number', sa.Text(), nullable=True))
    op.add_column('team_travel', sa.Column('need_airport_to_hotel_cab', sa.Boolean(), nullable=True))
    op.add_column('team_travel', sa.Column('need_hotel_to_airport_cab', sa.Boolean(), nullable=True))
    op.add_column('team_travel', sa.Column('need_accommodation', sa.Boolean(), nullable=True))
    op.add_column('team_travel', sa.Column('self_arranged_accommodation', sa.Boolean(), nullable=True))
    op.add_column('team_travel', sa.Column('emergency_contact_name', sa.Text(), nullable=True))
    op.add_column('team_travel', sa.Column('emergency_contact_phone', sa.Text(), nullable=True))
    travel_status_enum = postgresql.ENUM('draft', 'submitted', 'verified', 'processing', 'completed', name='travel_status_enum')
    travel_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('team_travel', sa.Column('travel_status', travel_status_enum, nullable=True))
    op.add_column('team_travel', sa.Column('travel_details_submitted_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('team_travel', sa.Column('travel_details_updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('team_travel', sa.Column('committee_notes', sa.Text(), nullable=True))
    op.add_column('team_travel', sa.Column('accommodation_assigned', sa.Boolean(), nullable=True))
    op.add_column('team_travel', sa.Column('hotel_name', sa.Text(), nullable=True))
    op.add_column('team_travel', sa.Column('hotel_address', sa.Text(), nullable=True))
    op.add_column('team_travel', sa.Column('hotel_room_number', sa.Text(), nullable=True))
    op.add_column('team_travel', sa.Column('hotel_checkin_time', sa.Text(), nullable=True))
    op.add_column('team_travel', sa.Column('cab_pickup_assigned', sa.Boolean(), nullable=True))
    op.add_column('team_travel', sa.Column('cab_drop_assigned', sa.Boolean(), nullable=True))
    op.add_column('team_travel', sa.Column('cab_driver_name', sa.Text(), nullable=True))
    op.add_column('team_travel', sa.Column('cab_driver_phone', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_travel', 'cab_driver_phone')
    op.drop_column('team_travel', 'cab_driver_name')
    op.drop_column('team_travel', 'cab_drop_assigned')
    op.drop_column('team_travel', 'cab_pickup_assigned')
    op.drop_column('team_travel', 'hotel_checkin_time')
    op.drop_column('team_travel', 'hotel_room_number')
    op.drop_column('team_travel', 'hotel_address')
    op.drop_column('team_travel', 'hotel_name')
    op.drop_column('team_travel', 'accommodation_assigned')
    op.drop_column('team_travel', 'committee_notes')
    op.drop_column('team_travel', 'travel_details_updated_at')
    op.drop_column('team_travel', 'travel_details_submitted_at')
    op.drop_column('team_travel', 'travel_status')
    travel_status_enum = postgresql.ENUM('draft', 'submitted', 'verified', 'processing', 'completed', name='travel_status_enum')
    travel_status_enum.drop(op.get_bind(), checkfirst=True)
    op.drop_column('team_travel', 'emergency_contact_phone')
    op.drop_column('team_travel', 'emergency_contact_name')
    op.drop_column('team_travel', 'self_arranged_accommodation')
    op.drop_column('team_travel', 'need_accommodation')
    op.drop_column('team_travel', 'need_hotel_to_airport_cab')
    op.drop_column('team_travel', 'need_airport_to_hotel_cab')
    op.drop_column('team_travel', 'pnr_number')
    op.drop_column('team_travel', 'flight_or_train_number')
    op.drop_column('team_travel', 'departure_airport_or_station')
    op.drop_column('team_travel', 'departure_time')
    op.drop_column('team_travel', 'departure_date')
    op.drop_column('team_travel', 'arrival_airport_or_station')
    op.drop_column('team_travel', 'arrival_time')
    op.drop_column('team_travel', 'arrival_date')
    # ### end Alembic commands ###
