"""create events table

Revision ID: 2c8ccddea995
Revises: f2a7a4a20165
Create Date: 2026-05-31 15:31:08.399045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c8ccddea995'
down_revision: Union[str, Sequence[str], None] = 'f2a7a4a20165'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score_anomalies', sa.Column('dimension', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('score_anomalies', 'dimension')
    # ### end Alembic commands ###
