"""Add combined ticket and is_locked

Revision ID: 5a5b8974cac6
Revises: 0df065ecb10a
Create Date: 2026-06-17 22:01:27.150140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a5b8974cac6'
down_revision: Union[str, Sequence[str], None] = '0df065ecb10a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_travel', sa.Column('combined_ticket_url', sa.Text(), nullable=True))
    op.add_column('team_travel', sa.Column('combined_ticket_name', sa.Text(), nullable=True))
    op.add_column('team_travel', sa.Column('combined_ticket_uploaded_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('team_travel', sa.Column('is_locked', sa.Boolean(), nullable=True))
    op.drop_column('team_travel', 'return_ticket_url')
    op.drop_column('team_travel', 'arrival_ticket_name')
    op.drop_column('team_travel', 'travel_processing_started')
    op.drop_column('team_travel', 'return_ticket_uploaded_at')
    op.drop_column('team_travel', 'return_ticket_name')
    op.drop_column('team_travel', 'arrival_ticket_uploaded_at')
    op.drop_column('team_travel', 'arrival_ticket_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_travel', sa.Column('arrival_ticket_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('team_travel', sa.Column('arrival_ticket_uploaded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('team_travel', sa.Column('return_ticket_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('team_travel', sa.Column('return_ticket_uploaded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('team_travel', sa.Column('travel_processing_started', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('team_travel', sa.Column('arrival_ticket_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('team_travel', sa.Column('return_ticket_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('team_travel', 'is_locked')
    op.drop_column('team_travel', 'combined_ticket_uploaded_at')
    op.drop_column('team_travel', 'combined_ticket_name')
    op.drop_column('team_travel', 'combined_ticket_url')
    # ### end Alembic commands ###
