"""add phone, org, and expertise to evaluators

Revision ID: 72ada51bc731
Revises: 87901e3a8af8
Create Date: 2026-05-31 23:43:23.624493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72ada51bc731'
down_revision: Union[str, Sequence[str], None] = '87901e3a8af8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluators', sa.Column('phone_number', sa.Text(), nullable=True))
    op.add_column('evaluators', sa.Column('organization', sa.Text(), nullable=True))
    op.add_column('evaluators', sa.Column('expertise', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluators', 'expertise')
    op.drop_column('evaluators', 'organization')
    op.drop_column('evaluators', 'phone_number')
    # ### end Alembic commands ###
