"""Add scheduled_for to communications

Revision ID: 87901e3a8af8
Revises: f430fbc74ad3
Create Date: 2026-05-31 17:28:09.128923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87901e3a8af8'
down_revision: Union[str, Sequence[str], None] = 'f430fbc74ad3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communications', sa.Column('scheduled_for', postgresql.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('communications', 'scheduled_for')
    # ### end Alembic commands ###
