"""Add travel reimbursement models

Revision ID: 90bb1271e091
Revises: 3c2bc1205a05
Create Date: 2026-06-17 19:56:59.706810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90bb1271e091'
down_revision: Union[str, Sequence[str], None] = '3c2bc1205a05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travel_reimbursement_claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('account_holder_name', sa.Text(), nullable=True),
    sa.Column('phone_number', sa.Text(), nullable=True),
    sa.Column('account_number', sa.Text(), nullable=True),
    sa.Column('ifsc_code', sa.Text(), nullable=True),
    sa.Column('bank_name', sa.Text(), nullable=True),
    sa.Column('branch_name', sa.Text(), nullable=True),
    sa.Column('claim_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('receipts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id')
    )
    op.add_column('team_travel', sa.Column('ticket_file_url', sa.Text(), nullable=True))
    op.add_column('team_travel', sa.Column('ticket_file_name', sa.Text(), nullable=True))
    op.add_column('team_travel', sa.Column('ticket_uploaded_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_travel', 'ticket_uploaded_at')
    op.drop_column('team_travel', 'ticket_file_name')
    op.drop_column('team_travel', 'ticket_file_url')
    op.drop_table('travel_reimbursement_claims')
    # ### end Alembic commands ###
