"""add event rules table

Revision ID: 935734134c9e
Revises: 134e6897411f
Create Date: 2026-05-30 17:51:37.927746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '935734134c9e'
down_revision: Union[str, Sequence[str], None] = '134e6897411f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_rules', 'title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('event_rules', 'category',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_index('ix_event_rules_event_id', table_name='event_rules')
    op.drop_index('ix_event_rules_id', table_name='event_rules')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_event_rules_id', 'event_rules', ['id'], unique=False)
    op.create_index('ix_event_rules_event_id', 'event_rules', ['event_id'], unique=False)
    op.alter_column('event_rules', 'category',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('event_rules', 'title',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
