"""create events table

Revision ID: f430fbc74ad3
Revises: 2c8ccddea995
Create Date: 2026-05-31 15:38:32.079946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f430fbc74ad3'
down_revision: Union[str, Sequence[str], None] = '2c8ccddea995'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score_anomalies', sa.Column('evaluation_id', sa.UUID(), nullable=True))
    op.add_column('score_anomalies', sa.Column('resolution', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'score_anomalies', 'evaluations', ['evaluation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'score_anomalies', type_='foreignkey')
    op.drop_column('score_anomalies', 'resolution')
    op.drop_column('score_anomalies', 'evaluation_id')
    # ### end Alembic commands ###
